org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Mapbox Downloads Token (overridden by developer's ~/.gradle/gradle.properties if set)
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoibXVyaGFmMTA2IiwiYSI6ImNtc3lsOTc3dzAwbHkyd3B4NGt0eGoyam8ifQ.RQ6f0j-oez-uAD21Ci3Btw
kotlin.incremental=false
